<?php
	//echo 'This is a simple custom module and it does not include admin and database realted files.';
?>

<form class="" action="<?php echo $block->getBaseUrl().'form/index/save'; ?>" id="customer-test-form" method="post">
    <h1>Enter the following  Customer details!</h1>
    <label>Name:</label><br>
    <input type="text" placeholder="Enter Name" name="name" id="name">
    <br>
    
    <label>Surname:</label><br>
    <input type="text" placeholder="Enter Last name" name="lname" id="lname">
    <br>
    
    <label>Email:</label><br>
    <input type="text" placeholder="Enter Email" name="email" id="email">
    <br>
    
    <label>MobNO:</label><br>
    <input type="text" placeholder="Enter Mobile number" name="mobno" id="mobno">
    <br>
    
    <label>Gender:</label><br>
    <input type="text" placeholder="Enter Gender" name="gender" id="gender">
    <br>

    <label>Address:</label><br>
    <input type="text" placeholder="Enter Adresss" name="addr" id="addr">
    <br>
    
    <label>State:</label><br>
    <input type="text" placeholder="Enter your State" name="state" id="state">
    <br>
    
    <label>City:</label><br>
    <input type="text" placeholder="Enter City" name="city" id="city">
    <br>
    
    <label>PinCode:</label><br>
    <input type="text" placeholder="Enter Pincode" name="pin" id="pin">
    <br>
    
    <button type="submit" title="Submit">Submit</button>

</form>